### ISSUE TITLE
IndexError: index 6 is out of bounds for axis 0 with size 6

### ISSUE THREAD

**Issue by Ulfzerk** [python-engineer/MLfromscratch#3]
Hi!

I tried yours naive bayes classifier on 
https://archive.ics.uci.edu/ml/machine-learning-databases/glass/glass.data

n_classes = len(self._classes) returns classes like [ 1,2,3,4,5,6 ] unlike in iris [0,1,2]

In loop 
for c in self._classes:
            X_c = X[y==c]
            self._mean[c, :] = X_c.mean(axis=0)
            self._var[c, :] = X_c.var(axis=0)
            self._priors[c] = X_c.shape[0] / float(n_samples)

I will try to go self._mean[6, ;] which will be out of boundry.
Shouldn't it be 
for index, c in enumerate(self._classes):
with index insteed of c in calculations?

**Comment by patrickloeber** [comment]
Thank yor for reporting this! I think you are correct

**Comment by patrickloeber** [comment]
I fixed it
