### ISSUE TITLE
Explanation of `get_hyperplane_value`

### ISSUE THREAD

**Issue by weilueluo** [python-engineer/MLfromscratch#4]
Hi, I find your tutorials on SVM very helpful but I do not understand the `get_hyperplane_value` method in `svm_tests.py`. May I have an explanation of it? Thank you!

**Comment by patrickloeber** [comment]
Hi, someone asked the same question in the comments below the video. you might want to have a look at this. i will post the same answer here:
Yes the important thing is the line equation in the so called normal form x0*w0 + x1*w1 = b (see https://sites.math.washington.edu/~king/coursedir/m445w04/notes/vector/equations.html). We want to solve this for x1 (probably the variable names are confusing here: x0 is our x axis, and x1, is our y axis). Then just take some points on the x axis, and use the equation to get the corresponding y points, and pass these points to matplotlib...
